VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'Private Sub Workbook_Deactivate()
'Dim ws As Worksheet: Set ws = Worksheets("vms")
'ws.Visible = xlSheetVeryHidden
'
'End Sub
'
'Private Sub Workbook_Open()
'Dim ws As Worksheet: Set ws = Worksheets("vms")
'ws.Visible = xlSheetVeryHidden
'
'End Sub

